"""Scenario economics for the top surviving opportunities.

These are SCENARIOS, not forecasts. Every input is tagged:
  FACT  = observed in a cited source (see reports/cycle-01.md sources)
  EST   = estimate derived from facts with stated arithmetic
  ASM   = assumption to be replaced by experiment data
Run: python research/economics.py > research/economics.md
"""

LABOUR_EUR_H = 40.0  # ASM: opportunity cost of the operator's hour

# AI cost per accepted invoice (EST): ~2,500 input + ~400 output tokens on claude-haiku-4-5 ($1/$5 per MTok, FACT);
# ASM 15% escalate to claude-opus-5 ($5/$25, FACT) with ~1,900 output tokens incl. adaptive thinking.
haiku = (2500 * 1 + 400 * 5) / 1e6
opus = (2500 * 5 + 1900 * 25) / 1e6
AI_USD_PER_INVOICE = haiku + 0.15 * opus
USD_EUR = 0.92  # ASM
AI_EUR_PER_INVOICE = AI_USD_PER_INVOICE * USD_EUR

MODELS = {
    "S1 Gestoría invoice-to-ledger automation": {
        "unit": "gestoría (monthly retainer)",
        "setup_fee": (1200, "ASM inside FACT range EUR 800-2,000 for OCR+integration implementations"),
        "setup_labour_h": (10, "ASM"),
        "monthly_price": (150, "ASM"),
        "monthly_variable": [
            ("AI model cost", 1500 * AI_EUR_PER_INVOICE, f"EST 1,500 invoices/mo (ASM) x EUR {AI_EUR_PER_INVOICE:.4f}"),
            ("human review", 1500 * 0.03 * (2 / 60) * LABOUR_EUR_H, "ASM 3% invoices to review, 2 min each"),
            ("infrastructure", 5, "ASM"),
            ("support/oversight", 1 * LABOUR_EUR_H, "ASM 1 h/mo"),
        ],
        "cac": (600, "ASM ~15 h outreach+demo per close"),
        "fixed_monthly": (100, "ASM tooling, domain, accounting"),
    },
    "S1b same, priced per invoice (EUR 0.20 x 1,500/mo)": {
        "unit": "gestoría (usage-priced)",
        "setup_fee": (1200, "ASM"),
        "setup_labour_h": (10, "ASM"),
        "monthly_price": (300, "ASM EUR 0.20/invoice x 1,500 invoices"),
        "monthly_variable": [
            ("AI model cost", 1500 * AI_EUR_PER_INVOICE, "EST"),
            ("human review", 1500 * 0.03 * (2 / 60) * LABOUR_EUR_H, "ASM"),
            ("infrastructure", 5, "ASM"),
            ("support/oversight", 1 * LABOUR_EUR_H, "ASM"),
        ],
        "cac": (600, "ASM"),
        "fixed_monthly": (100, "ASM"),
    },
    "S2 Contracted-power audit (success fee)": {
        "unit": "audited supply (one-off)",
        "setup_fee": (0, "free audit"),
        "setup_labour_h": (1.5, "ASM data collection + review of tool output"),
        "one_off_price": (0.25 * 600, "ASM 25% of median first-year saving; median saving EUR 600 is ASM (kill if < 600)"),
        "monthly_price": (0, ""),
        "monthly_variable": [],
        "partner_share": (0.20, "ASM rev-share to referring gestoría"),
        "cac": (20, "ASM when sourced via gestoría partner; direct outreach far higher"),
        "fixed_monthly": (50, "ASM"),
    },
    "S4 AI-assisted memoria técnica studio": {
        "unit": "tender memoria (one-off)",
        "setup_fee": (0, ""),
        "setup_labour_h": (6, "ASM human editing per memoria with AI draft"),
        "one_off_price": (700, "ASM inside FACT range EUR 350-5,000"),
        "ai_per_job": (8, "EST long-context drafting on claude-opus-5, ~200k in / 40k out tokens"),
        "monthly_price": (0, ""),
        "monthly_variable": [],
        "cac": (150, "ASM"),
        "fixed_monthly": (100, "ASM"),
    },
}


def monthly_unit(m):
    var = sum(v for _, v, _ in m["monthly_variable"])
    return m["monthly_price"][0], var


def one_off_margin(m):
    price = m.get("one_off_price", (0,))[0] + m["setup_fee"][0]
    cost = m["setup_labour_h"][0] * LABOUR_EUR_H + m.get("ai_per_job", (0,))[0]
    price_net = price * (1 - m.get("partner_share", (0,))[0])
    return price_net, cost


def main():
    print("# Scenario economics (generated by research/economics.py)\n")
    print(f"AI cost per accepted invoice (EST): ${AI_USD_PER_INVOICE:.4f} = EUR {AI_EUR_PER_INVOICE:.4f} "
          f"(haiku ${haiku:.4f}; opus escalation ${opus:.4f} x 15%).\n")
    for name, m in MODELS.items():
        print(f"## {name}\n\nUnit: {m['unit']}\n")
        print("| input | value | basis |\n|---|---|---|")
        for k in ["setup_fee", "setup_labour_h", "monthly_price", "one_off_price", "ai_per_job", "partner_share", "cac", "fixed_monthly"]:
            if k in m and m[k][1]:
                print(f"| {k} | {m[k][0]} | {m[k][1]} |")
        for label, v, basis in m["monthly_variable"]:
            print(f"| monthly {label} | {v:.2f} | {basis} |")
        rev_m, var_m = monthly_unit(m)
        one_rev, one_cost = one_off_margin(m)
        cac, fixed = m["cac"][0], m["fixed_monthly"][0]
        print()
        if rev_m:
            cm = rev_m - var_m
            print(f"Monthly contribution per customer: EUR {cm:.2f} ({cm / rev_m:.0%} of price). "
                  f"One-off setup margin: EUR {one_rev - one_cost:.2f}. "
                  f"CAC payback: {'immediate (setup margin covers CAC)' if one_rev - one_cost >= cac else f'{(cac - (one_rev - one_cost)) / cm:.1f} months'}.\n")
            print("| customers | revenue/yr | contribution/yr (after fixed) | break-even? |\n|---|---|---|---|")
            for n in [10, 50, 100, 500, 1000]:
                # steady state: customers active all year, 1/3 new each year (ASM) paying setup and CAC
                new = n / 3
                rev = n * rev_m * 12 + new * one_rev
                contrib = n * cm * 12 + new * (one_rev - one_cost - cac) - fixed * 12
                print(f"| {n} | {rev:,.0f} | {contrib:,.0f} | {'yes' if contrib > 0 else 'no'} |")
        else:
            unit = one_rev - one_cost - cac
            print(f"Contribution per job: EUR {unit:.2f} (net price {one_rev:.2f} - delivery {one_cost:.2f} - CAC {cac}). "
                  f"Break-even jobs per month: {fixed / unit:.1f}.\n" if unit > 0 else
                  f"Contribution per job is NEGATIVE (EUR {unit:.2f}): kill unless price or delivery cost changes.\n")
            print("| jobs per year | revenue/yr | contribution/yr (after fixed) |\n|---|---|---|")
            for n in [10, 50, 100, 500, 1000]:
                print(f"| {n} | {n * one_rev:,.0f} | {n * unit - fixed * 12:,.0f} |")
        print()


if __name__ == "__main__":
    main()
