"""Cycle 02 pilot economics: TOTAL cost per accepted invoice, pricing models, funnel/CAC, and
what the validation thresholds can and cannot prove.

Every input is labelled: SRC (source-backed estimate), WEAK, ASM (assumption), UNK (unknown).
Run: python research/pilot_economics.py > research/pilot_economics.md
"""
import itertools
import math
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parents[1]))
from invoice_pipeline.evaluate import wilson, required_n  # noqa: E402

USD_EUR = 0.92                                   # ASM
HAIKU_EUR = (2500 * 1 + 400 * 5) / 1e6 * USD_EUR  # EST from model prices ($1/$5 per MTok) and ASM token counts
OPUS_EUR = (2500 * 5 + 1900 * 25) / 1e6 * USD_EUR  # EST ($5/$25) incl. adaptive thinking tokens (ASM)
OPERATOR_EUR_H = 40.0                            # ASM: your hour
# SRC: IX Convenio gestorías administrativas: 1,780 h/year; technical staff ~€25-26k/year (BOE-A-2024-17575);
# admin staff assumed ~€20k; employer social security ~31.5% (ASM) -> ~€15/h loaded.
STAFF_EUR_H = 20000 * 1.315 / 1780


def unit_cost(escalation, exception, review_min, reviewer_eur_h, audit_share=0.05, audit_min=1.0,
              reprocess=0.02, infra_month=20.0, support_h_month=1.5, volume=1000):
    """Total € per ACCEPTED invoice, monthly, for one customer."""
    model = volume * (HAIKU_EUR + escalation * OPUS_EUR) * (1 + reprocess)
    accepted = volume * (1 - exception)
    review = volume * exception * review_min / 60 * reviewer_eur_h
    audit = accepted * audit_share * audit_min / 60 * reviewer_eur_h  # spot checks catch consistent misreads
    fixed = infra_month + support_h_month * OPERATOR_EUR_H
    total = model + review + audit + fixed
    return {"accepted": accepted, "model": model, "review": review, "audit": audit, "fixed": fixed,
            "total": total, "per_accepted": total / accepted}


def pricing(volume):
    return {
        "per invoice €0.10": 0.10 * volume,
        "per invoice €0.20": 0.20 * volume,
        "per invoice €0.30": 0.30 * volume,
        "tiers €99/€199/€349 (≤500/≤1500/≤4000)": 99 if volume <= 500 else 199 if volume <= 1500 else 349,
        "hybrid €49 + €0.10/invoice": 49 + 0.10 * volume,
        "setup €600 (amortised 12 mo) + €149/mo": 600 / 12 + 149,
    }


def main():
    print("# Pilot economics — cycle 02 (generated by research/pilot_economics.py)\n")
    print("Labels: SRC source-backed estimate · WEAK · ASM assumption · UNK unknown. Nothing here is measured yet.\n")
    print("| input | value | label |\n|---|---|---|")
    for k, v, lab in [("Haiku extraction cost / document", f"€{HAIKU_EUR:.4f}", "EST from list prices + ASM tokens"),
                      ("Opus escalation cost / document", f"€{OPUS_EUR:.4f}", "EST from list prices + ASM tokens"),
                      ("Your hour", f"€{OPERATOR_EUR_H:.0f}", "ASM"),
                      ("Gestoría staff hour (loaded)", f"€{STAFF_EUR_H:.2f}", "SRC hours (convenio) + ASM salary/SS"),
                      ("Exception (human review) rate", "5% / 15% / 30%", "UNK — the pilot measures it"),
                      ("Review minutes per exception", "2 / 4", "ASM"),
                      ("Audit sampling of accepted invoices", "5% × 1 min", "ASM — needed because validation misses consistent misreads"),
                      ("Reprocessing overhead", "2% of model cost", "ASM"),
                      ("Infrastructure per customer", "€20/month", "ASM"),
                      ("Support per customer", "1.5 h/month of your time", "ASM"),
                      ("Volume per customer", "1,000 invoices/month", "ASM (UNK)")]:
        print(f"| {k} | {v} | {lab} |")

    print("\n## 1. Total cost per accepted invoice (1,000 invoices/month)\n")
    print("| who reviews | exception rate | review min | model €/mo | review €/mo | audit €/mo | fixed €/mo | **total € / accepted invoice** |")
    print("|---|---|---|---|---|---|---|---|")
    rows = {}
    for who, rate in [("you (service)", OPERATOR_EUR_H), ("gestoría staff (software)", STAFF_EUR_H)]:
        for exc, rm in itertools.product([0.05, 0.15, 0.30], [2, 4]):
            u = unit_cost(0.15, exc, rm, rate)
            rows[(who, exc, rm)] = u
            print(f"| {who} | {exc:.0%} | {rm} | {u['model']:.2f} | {u['review']:.2f} | {u['audit']:.2f} | {u['fixed']:.2f} | **{u['per_accepted']:.3f}** |")
    print("\nThe model is under €20/month in every case. **Human review and your fixed support time are the cost.** "
          "If the gestoría's staff do the reviews, the review cost moves to the customer: it lowers our cost "
          "and it also lowers the value we deliver.\n")

    print("## 2. Pricing models (service model: you review; exception 15%, 3 min/exception)\n")
    print("| pricing | 300 inv/mo: revenue | contribution | 1,000 inv/mo: revenue | contribution | 3,000 inv/mo: revenue | contribution |")
    print("|---|---|---|---|---|---|---|")
    for name in pricing(1000):
        cells = []
        for vol in [300, 1000, 3000]:
            u = unit_cost(0.15, 0.15, 3, OPERATOR_EUR_H, volume=vol)
            rev = pricing(vol)[name]
            cells += [f"€{rev:,.0f}", f"€{rev - u['total']:,.0f} ({(rev - u['total']) / rev:.0%})"]
        print(f"| {name} | " + " | ".join(cells) + " |")
    print("\nCustomer's own cost of manual entry for comparison: 1-3 min per invoice (WEAK: vendor blogs) × "
          f"€{STAFF_EUR_H:.2f}/h = **€{1 / 60 * STAFF_EUR_H:.2f}-€{3 / 60 * STAFF_EUR_H:.2f} per invoice**. "
          "Competitor prices could not be retrieved here (pages blocked): **UNK**, and they set the real ceiling.\n")

    print("## 2b. Software model: the gestoría's staff review exceptions (1,000 invoices/month)\n")
    print("Our cost = model + infrastructure + your support time. The customer's net saving = manual-entry cost avoided "
          "− our price − their own review and audit time.\n")
    print("| exception rate | price / invoice | our cost / invoice | our contribution / month | customer net saving / invoice (1 min manual) | (3 min manual) |")
    print("|---|---|---|---|---|---|")
    for exc in [0.05, 0.15, 0.30]:
        u = unit_cost(0.15, exc, 3, STAFF_EUR_H)
        ours = (u["model"] + u["fixed"]) / 1000
        cust_review = (u["review"] + u["audit"]) / 1000
        for price in [0.10, 0.20, 0.30]:
            save1 = 1 / 60 * STAFF_EUR_H - price - cust_review
            save3 = 3 / 60 * STAFF_EUR_H - price - cust_review
            print(f"| {exc:.0%} | €{price:.2f} | €{ours:.3f} | €{(price - ours) * 1000:,.0f} | €{save1:+.2f} | €{save3:+.2f} |")
    print("\nThe software model can have a positive margin for us, but only if exceptions stay low **and** manual entry "
          "really takes ~3 minutes. At 1 minute per invoice the customer loses money at any price shown.\n")

    print("## 3. Funnel, CAC and payback (all ASM; 25 qualified conversations)\n")
    print("| scenario | reply→conversation | conversation→sample run | sample→paid pilot | paid pilots | your hours | CAC per paid pilot | monthly contribution (software model, €0.20, 1,000 inv) | payback |")
    print("|---|---|---|---|---|---|---|---|---|")
    u_sw = unit_cost(0.15, 0.15, 3, STAFF_EUR_H)
    contrib = pricing(1000)["per invoice €0.20"] - (u_sw["model"] + u_sw["fixed"])  # software model: customer reviews
    for name, reach, samp, paid in [("low", 150, 0.20, 0.20), ("base", 100, 0.32, 0.35), ("high", 60, 0.48, 0.50)]:
        # reach = contact attempts needed to hold 25 conversations
        sample_runs = 25 * samp
        paid_pilots = sample_runs * paid
        hours = reach * 0.15 + 25 * 0.75 + sample_runs * 3 + paid_pilots * 6
        cac = hours * OPERATOR_EUR_H / paid_pilots if paid_pilots else float("inf")
        pb = cac / contrib if contrib > 0 else float("inf")
        print(f"| {name} | {25 / reach:.0%} | {samp:.0%} | {paid:.0%} | {paid_pilots:.1f} | {hours:.0f} | €{cac:,.0f} | €{contrib:,.0f} | {pb:.1f} months |")
    print("\nHours: 9 min per contact attempt, 45 min per conversation, 3 h per sample run, 6 h to onboard a paid pilot (all ASM).\n")

    print("## 4. What the validation thresholds can prove\n")
    lo, hi = wilson(2, 25)
    lo0, hi0 = wilson(0, 25)
    print(f"- **2 paid pilots out of 25 conversations** → 95% interval for the true conversion rate: **{lo:.1%} to {hi:.1%}**. "
          "It proves that *someone* pays. It does not estimate a conversion rate you could plan with.")
    print(f"- **0 of 25** → the interval is 0% to {hi0:.1%}: conversion could still be as high as ~13%. A kill at 0/25 is a "
          "business judgement (CAC too high), not a statistical proof of no demand.")
    print("- **≥97% accuracy**: invoices you need so that the 95% lower bound clears 97%, by true accuracy:")
    print("\n| true invoice-level accuracy | invoices needed |\n|---|---|")
    for p in [0.975, 0.98, 0.985, 0.99, 0.995]:
        print(f"| {p:.1%} | {required_n(p, 0.97)} |")
    print("\nA 20-50 invoice sample can **reject** an accuracy claim (e.g. 5 errors in 50 means accuracy is almost certainly "
          "below 97%). It cannot **confirm** one. The pilot report must show counts and intervals, not a single percentage.")
    print("\n- **Economic meaning**: in the software model at €0.20 × 1,000 invoices, one customer contributes "
          f"~€{contrib:,.0f}/month. Two customers pay for about {2 * contrib / OPERATOR_EUR_H:.0f} h of your time per month. "
          "The pilot validates willingness to pay, not a business. In the service model (you review), contribution is negative "
          "at every tested price.")


if __name__ == "__main__":
    main()
